### ISSUE TITLE
Unable to change config.js

### ISSUE THREAD

**Issue by ZeeCas** [kholmogorov27/chevron#6]
Hi! It might just be me making a stupid mistake, but I can't seem to edit the config.js file. Editing it after building seems to have zero effect on the macros/commands. Is there something simple that I'm missing?

**Comment by ZeeCas** [comment]
I am a fool. You edit the config.js in the public folder.

**Comment by kholmogorov27** [comment]
The `/public` folder is used for development. After building all the files from `/public` folder copy to the `/dist` folder.
When you open Chevron in browser it uses files only from the `/dist` folder.

I recommend editing `/dist/config.js` because it doesn't require rebuilding. 
However you can edit `public/config.js` too but you have to rebuild to apply these changes.
**WARNING**: Building process overwrites `/dist/config.js`

*NOTE*: Release archives consist of files from the `/dist` folder
